services:
  postgres:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_DB: tripplanner
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: tripplanner-postgres

volumes:
  postgres_data: